// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHw9qLYsl7V0l-gAUxY_z9RgzCBVf6gg4',
    appId: '1:428183904453:web:c6e54eebee879e8acc90ac',
    messagingSenderId: '428183904453',
    projectId: 'octy-habits',
    authDomain: 'octy-habits.firebaseapp.com',
    storageBucket: 'octy-habits.firebasestorage.app',
    measurementId: 'G-JBV9XXKESR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihz8B-OyUbviiBXewBdF2D_6oD8ubDR0',
    appId: '1:428183904453:android:34a8112e29ff5c26cc90ac',
    messagingSenderId: '428183904453',
    projectId: 'octy-habits',
    storageBucket: 'octy-habits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1hPD85xHSaCzgII4_cqN5XRFZQvzJxCo',
    appId: '1:428183904453:ios:005e9bd191547406cc90ac',
    messagingSenderId: '428183904453',
    projectId: 'octy-habits',
    storageBucket: 'octy-habits.firebasestorage.app',
    iosBundleId: 'com.example.octyHabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1hPD85xHSaCzgII4_cqN5XRFZQvzJxCo',
    appId: '1:428183904453:ios:005e9bd191547406cc90ac',
    messagingSenderId: '428183904453',
    projectId: 'octy-habits',
    storageBucket: 'octy-habits.firebasestorage.app',
    iosBundleId: 'com.example.octyHabits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHw9qLYsl7V0l-gAUxY_z9RgzCBVf6gg4',
    appId: '1:428183904453:web:fc68c5a8e48546accc90ac',
    messagingSenderId: '428183904453',
    projectId: 'octy-habits',
    authDomain: 'octy-habits.firebaseapp.com',
    storageBucket: 'octy-habits.firebasestorage.app',
    measurementId: 'G-00GCPRC65M',
  );
}
